# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neo4j-gds.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fneo4j-gds.proto\x12\tneo4j_gds\"\x92\x01\n\x08Property\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x30\n\nvalue_type\x18\x02 \x02(\x0e\x32\x1c.neo4j_gds.PropertyValueType\x12\x13\n\tvalue_str\x18\x03 \x01(\tH\x00\x12\x13\n\tvalue_int\x18\x04 \x01(\x03H\x00\x12\x13\n\tvalue_dbl\x18\x05 \x01(\x01H\x00\x42\x07\n\x05value\"P\n\x04Node\x12\x0f\n\x07node_id\x18\x01 \x02(\x03\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12\'\n\nproperties\x18\x03 \x03(\x0b\x32\x13.neo4j_gds.Property\"m\n\x04\x45\x64ge\x12\x16\n\x0esource_node_id\x18\x01 \x02(\x03\x12\x16\n\x0etarget_node_id\x18\x02 \x02(\x03\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\'\n\nproperties\x18\x04 \x03(\x0b\x32\x13.neo4j_gds.Property*G\n\x11PropertyValueType\x12\x0f\n\x0bTYPE_STRING\x10\x00\x12\x10\n\x0cTYPE_INTEGER\x10\x01\x12\x0f\n\x0bTYPE_DOUBLE\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neo4j_gds_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROPERTYVALUETYPE']._serialized_start=372
  _globals['_PROPERTYVALUETYPE']._serialized_end=443
  _globals['_PROPERTY']._serialized_start=31
  _globals['_PROPERTY']._serialized_end=177
  _globals['_NODE']._serialized_start=179
  _globals['_NODE']._serialized_end=259
  _globals['_EDGE']._serialized_start=261
  _globals['_EDGE']._serialized_end=370
# @@protoc_insertion_point(module_scope)
