services:
  neo4j:
    image: neo4j:5.13-enterprise
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
      - 8491:8491
    volumes:
      - ./data:/var/lib/neo4j/data
      - ./certificates:/var/lib/neo4j/certificates
      - ./licenses:/var/lib/neo4j/licenses
    environment:
      NEO4J_AUTH: "neo4j/passw0rd"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_PLUGINS: '[ "graph-data-science" ]'
      NEO4J_server_memory_heap_max__size: "16G"
      NEO4J_gds_enterprise_license__file: "/var/lib/neo4j/licenses/gds.license"
      NEO4J_dbms_security_procedures_unrestricted: "gds.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*"
      NEO4J_gds_arrow_enabled: "true"
      NEO4J_gds_arrow_listen__address: "0.0.0.0"
      NEO4J_gds_arrow_advertised__listen__address: "ali.neo4j.ninja"
      NEO4J_server_default__listen__address: "0.0.0.0"
      NEO4J_server_default__advertised__address: "ali.neo4j.ninja"
      NEO4J_dbms_ssl_policy_https_enabled: "true"
      NEO4J_dbms_ssl_policy_https_base__directory: "/var/lib/neo4j/certificates"
      NEO4J_dbms_ssl_policy_https_private__key: "private.key"
      NEO4J_dbms_ssl_policy_https.public__certificate: "public.crt"
      NEO4J_dbms_ssl_policy_bolt_enabled: "true"
      NEO4J_dbms_ssl_policy_bolt_base__directory: "/var/lib/neo4j/certificates"
      NEO4J_dbms_ssl_policy_bolt_private__key: "private.key"
      NEO4J_dbms_ssl_policy_bolt_public__certificate: "public.crt"
      NEO4J_server_bolt_tls__level: "OPTIONAL"
